import { Planet } from './types';

export const planets: Planet[] = [
  {
    id: 'sun',
    name: 'Le Soleil',
    subtitle: 'L\'étoile au centre de notre système solaire',
    description: 'Le Soleil est l\'étoile au centre de notre système solaire. Il représente 99,86 % de la masse totale du système solaire et fournit l\'énergie nécessaire à la vie sur Terre.',
    image: '/sun.png',
    facts: {
      'Type': 'Étoile naine jaune',
      'Âge': '4.6 milliards d\'années',
      'Température de surface': '5 500°C',
      'Diamètre': '1.4 million km',
    },
  },
  {
    id: 'mercury',
    name: 'Mercure',
    subtitle: 'La planète la plus proche du Soleil',
    description: 'Mercure est la planète la plus proche du Soleil et la plus petite du Système solaire. Sa surface est criblée de cratères, similaire à celle de la Lune.',
    image: '/mercury.png',
    facts: {
      'Distance du Soleil': '57.9 millions km',
      'Période orbitale': '88 jours',
      'Température': '-180°C à 430°C',
      'Diamètre': '4 879 km',
    },
  },
  {
    id: 'venus',
    name: 'Vénus',
    subtitle: 'La planète la plus chaude',
    description: 'Vénus est souvent appelée la jumelle de la Terre en raison de leur taille similaire, mais son atmosphère dense crée un effet de serre intense.',
    image: '/venus.png',
    facts: {
      'Distance du Soleil': '108.2 millions km',
      'Période orbitale': '225 jours',
      'Température': '462°C',
      'Diamètre': '12 104 km',
    },
  },
  {
    id: 'earth',
    name: 'Terre',
    subtitle: 'Notre planète bleue',
    description: 'La Terre est la seule planète connue abritant la vie. Elle est caractérisée par ses océans d\'eau liquide et son atmosphère riche en oxygène.',
    image: '/earth.png',
    facts: {
      'Distance du Soleil': '149.6 millions km',
      'Période orbitale': '365.25 jours',
      'Température moyenne': '15°C',
      'Diamètre': '12 742 km',
    },
  },
  {
    id: 'mars',
    name: 'Mars',
    subtitle: 'La planète rouge',
    description: 'Mars fascine l\'humanité depuis des siècles. Ses calottes polaires et ses vallées suggèrent la présence passée d\'eau liquide à sa surface.',
    image: '/mars.png',
    facts: {
      'Distance du Soleil': '227.9 millions km',
      'Période orbitale': '687 jours',
      'Température': '-63°C',
      'Diamètre': '6 779 km',
    },
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    subtitle: 'Le géant gazeux',
    description: 'Jupiter est la plus grande planète du Système solaire. Sa Grande Tache Rouge est une tempête qui dure depuis au moins 400 ans.',
    image: '/jupiter.png',
    facts: {
      'Distance du Soleil': '778.5 millions km',
      'Période orbitale': '11.9 ans',
      'Température': '-110°C',
      'Diamètre': '139 820 km',
    },
  },
  {
    id: 'saturn',
    name: 'Saturne',
    subtitle: 'La planète aux anneaux',
    description: 'Saturne est célèbre pour ses magnifiques anneaux composés principalement de glace et de poussières.',
    image: '/saturne.png',
    facts: {
      'Distance du Soleil': '1.4 milliard km',
      'Période orbitale': '29.5 ans',
      'Température': '-140°C',
      'Diamètre': '116 460 km',
    },
  },
  {
    id: 'uranus',
    name: 'Uranus',
    subtitle: 'La planète couchée',
    description: 'Uranus est unique car son axe de rotation est presque parallèle au plan de son orbite, comme si elle était couchée sur le côté.',
    image: '/uranus.png',
    facts: {
      'Distance du Soleil': '2.9 milliards km',
      'Période orbitale': '84 ans',
      'Température': '-195°C',
      'Diamètre': '50 724 km',
    },
  },
  {
    id: 'neptune',
    name: 'Neptune',
    subtitle: 'La planète des vents',
    description: 'Neptune est connue pour ses vents les plus rapides du système solaire, atteignant 2 100 km/h.',
    image: '/neptune.png',
    facts: {
      'Distance du Soleil': '4.5 milliards km',
      'Période orbitale': '165 ans',
      'Température': '-200°C',
      'Diamètre': '49 244 km',
    },
  },
  {
    id: 'pluton',
    name: 'Pluton',
    subtitle: 'La planète naine glacée',
    description: 'Bien que déclassée au rang de planète naine en 2006, Pluton reste un objet fascinant de notre système solaire, avec ses glaciers d\'azote et son atmosphère ténue.',
    image: '/pluton.png',
    facts: {
      'Distance du Soleil': '5.9 milliards km',
      'Période orbitale': '248 ans',
      'Température': '-230°C',
      'Diamètre': '2 377 km',
    },
  },
];