import { Planet } from './types';

export const planets: Planet[] = [
  {
    id: 'sun',
    name: 'Le Soleil',
    subtitle: 'L\'étoile au centre de notre système solaire',
    description: 'Le Soleil est l\'étoile au centre de notre système solaire. Il représente 99,86 % de la masse totale du système solaire et fournit l\'énergie nécessaire à la vie sur Terre.',
    image: '/sun.png',
    facts: {
      'Type': 'Étoile naine jaune',
      'Âge': '4.6 milliards d\'années',
      'Température de surface': '5 500°C',
      'Diamètre': '1.4 million km',
      'Distance de la Terre': '150 millions km',
      'Temps pour la lumière à atteindre la Terre': '8 minutes',
      'Masse': '1.989 x 10^30 kg',
      'Composition': 'Hydrogène (74%) et hélium (24%)',
    },
  },
  {
    id: 'mercury',
    name: 'Mercure',
    subtitle: 'La planète la plus proche du Soleil',
    description: 'Mercure est la planète la plus proche du Soleil et la plus petite du Système solaire. Sa surface est criblée de cratères, similaire à celle de la Lune.',
    image: '/mercury.png',
    facts: {
      'Distance du Soleil': '57.9 millions km',
      'Période orbitale': '88 jours',
      'Température': '-180°C à 430°C',
      'Diamètre': '4 879 km',
      'Gravité': '0.38 g',
      'Atmosphère': 'Très fine',
      'Nombre de satellites': '0',
      'Durée d\'une journée (rotation)': '59 jours terrestres',
    },
  },
  {
    id: 'venus',
    name: 'Vénus',
    subtitle: 'La planète la plus chaude',
    description: 'Vénus est souvent appelée la jumelle de la Terre en raison de leur taille similaire, mais son atmosphère dense crée un effet de serre intense.',
    image: '/venus.png',
    facts: {
      'Distance du Soleil': '108.2 millions km',
      'Période orbitale': '225 jours',
      'Température': '462°C',
      'Diamètre': '12 104 km',
      'Atmosphère': 'Dioxyde de carbone (96%)',
      'Pression atmosphérique': '92 fois celle de la Terre',
      'Gravité': '0.9 g',
      'Durée d\'une journée (rotation)': '243 jours terrestres (rétrograde)',
    },
  },
  {
    id: 'earth',
    name: 'Terre',
    subtitle: 'Notre planète bleue',
    description: 'La Terre est la seule planète connue abritant la vie. Elle est caractérisée par ses océans d\'eau liquide et son atmosphère riche en oxygène.',
    image: '/earth.png',
    facts: {
      'Distance du Soleil': '149.6 millions km',
      'Période orbitale': '365.25 jours',
      'Température moyenne': '15°C',
      'Diamètre': '12 742 km',
      'Gravité': '1 g',
      'Nombre de satellites': '1 (La Lune)',
      'Pourcentage d\'eau en surface': '71%',
      'Âge approximatif': '4.54 milliards d\'années',
    },
  },
  {
    id: 'mars',
    name: 'Mars',
    subtitle: 'La planète rouge',
    description: 'Mars fascine l\'humanité depuis des siècles. Ses calottes polaires et ses vallées suggèrent la présence passée d\'eau liquide à sa surface.',
    image: '/mars.png',
    facts: {
      'Distance du Soleil': '227.9 millions km',
      'Période orbitale': '687 jours',
      'Température': '-63°C',
      'Diamètre': '6 779 km',
      'Atmosphère': 'Dioxyde de carbone (95%)',
      'Nombre de satellites': '2 (Phobos et Déimos)',
      'Gravité': '0.38 g',
      'Présence passée d\'eau': 'Oui, confirmée',
    },
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    subtitle: 'Le géant gazeux',
    description: 'Jupiter est la plus grande planète du Système solaire. Sa Grande Tache Rouge est une tempête qui dure depuis au moins 400 ans.',
    image: '/jupiter.png',
    facts: {
      'Distance du Soleil': '778.5 millions km',
      'Période orbitale': '11.9 ans',
      'Température': '-110°C',
      'Diamètre': '139 820 km',
      'Gravité': '2.53 g',
      'Nombre de satellites': '79',
      'Composition': 'Hydrogène (90%) et hélium (10%)',
      'Grande Tache Rouge': 'Tempête de 16 350 km de large',
    },
  },
  {
    id: 'saturn',
    name: 'Saturne',
    subtitle: 'La planète aux anneaux',
    description: 'Saturne est célèbre pour ses magnifiques anneaux composés principalement de glace et de poussières.',
    image: '/saturne.png',
    facts: {
      'Distance du Soleil': '1.4 milliard km',
      'Période orbitale': '29.5 ans',
      'Température': '-140°C',
      'Diamètre': '116 460 km',
      'Gravité': '1.06 g',
      'Nombre de satellites': '83',
      'Composition des anneaux': 'Glace et poussières',
      'Atmosphère': 'Hydrogène (96%) et hélium (3%)',
    },
  },
  {
    id: 'uranus',
    name: 'Uranus',
    subtitle: 'La planète couchée',
    description: 'Uranus est unique car son axe de rotation est presque parallèle au plan de son orbite, comme si elle était couchée sur le côté.',
    image: '/uranus.png',
    facts: {
      'Distance du Soleil': '2.9 milliards km',
      'Période orbitale': '84 ans',
      'Température': '-195°C',
      'Diamètre': '50 724 km',
      'Gravité': '0.89 g',
      'Inclinaison de l\'axe': '97.8°',
      'Nombre de satellites': '27',
      'Atmosphère': 'Hydrogène, hélium et méthane',
    },
  },
  {
    id: 'neptune',
    name: 'Neptune',
    subtitle: 'La planète des vents',
    description: 'Neptune est connue pour ses vents les plus rapides du système solaire, atteignant 2 100 km/h.',
    image: '/neptune.png',
    facts: {
      'Distance du Soleil': '4.5 milliards km',
      'Période orbitale': '165 ans',
      'Température': '-200°C',
      'Diamètre': '49 244 km',
      'Gravité': '1.14 g',
      'Nombre de satellites': '14',
      'Atmosphère': 'Hydrogène, hélium et méthane',
      'Durée d\'une journée': '16 heures',
    },
  },
  {
    id: 'pluton',
    name: 'Pluton',
    subtitle: 'La planète naine glacée',
    description: 'Bien que déclassée au rang de planète naine en 2006, Pluton reste un objet fascinant de notre système solaire, avec ses glaciers d\'azote et son atmosphère ténue.',
    image: '/pluton.png',
    facts: {
      'Distance du Soleil': '5.9 milliards km',
      'Période orbitale': '248 ans',
      'Température': '-230°C',
      'Diamètre': '2 377 km',
      'Gravité': '0.063 g',
      'Atmosphère': 'Azote, méthane et monoxyde de carbone',
      'Nombre de satellites': '5',
      'Classification': 'Planète naine (depuis 2006)',
    },
  },
];
